# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='message.proto',
  package='',
  serialized_pb='\n\rmessage.proto\"e\n\x07\x43ityAoi\x12&\n\x06player\x18\x01 \x03(\x0b\x32\x16.CityAoi.PlayerCityAoi\x1a\x32\n\rPlayerCityAoi\x12\x0f\n\x07role_id\x18\x01 \x01(\x05\x12\x10\n\x08target_x\x18\x02 \x01(\x05')




_CITYAOI_PLAYERCITYAOI = descriptor.Descriptor(
  name='PlayerCityAoi',
  full_name='CityAoi.PlayerCityAoi',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='role_id', full_name='CityAoi.PlayerCityAoi.role_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='target_x', full_name='CityAoi.PlayerCityAoi.target_x', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=68,
  serialized_end=118,
)

_CITYAOI = descriptor.Descriptor(
  name='CityAoi',
  full_name='CityAoi',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='player', full_name='CityAoi.player', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CITYAOI_PLAYERCITYAOI, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=17,
  serialized_end=118,
)

_CITYAOI_PLAYERCITYAOI.containing_type = _CITYAOI;
_CITYAOI.fields_by_name['player'].message_type = _CITYAOI_PLAYERCITYAOI
DESCRIPTOR.message_types_by_name['CityAoi'] = _CITYAOI

class CityAoi(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class PlayerCityAoi(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CITYAOI_PLAYERCITYAOI
    
    # @@protoc_insertion_point(class_scope:CityAoi.PlayerCityAoi)
  DESCRIPTOR = _CITYAOI
  
  # @@protoc_insertion_point(class_scope:CityAoi)

# @@protoc_insertion_point(module_scope)
